language: python
python:
- '3.7'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: Mo7oBz0Ocv1ibPmBMUi13jkF257wB4KBQZtWQfN/VMGuHaJyFIpeTKNkuQCdr3We8uNX0FnV7sX6Dj6MYi2rE3qzGzGDVU5rRYfidhZbgxeTm3CornRsD0u+BxG2N4/q0ELoI4hWEM3ZIBoeOpQ+jjR8U7YSfKlkPzqwyg8kb/o0YXMOyxhEO9mz/3/WWboHW6u6vFzwmanCsnejWt72S2QU5NrnVTo3yWrIyR2eLfktElFkFf1jXsWAGvoHiaWYFUdC1ehyArMQDrT3RXcF7yjn5NbV6UOjvXXQ52x3pZ9pHoQEBR68gRcLXti3Wos3DhcFPPa5IhG+QewIYP4Pj8si2aQ4VbOdq5hLVUUHXFzsk8jQgoa/i5wVqHWyMDq+3pBy1wLXNWEoO4VeaxyIGJhu3njE+CyX5rRkP7aHRH+eOHfBHP4k7hAza6iZBbH/4/uiZIThyqaWsFFNNO/vVlw4sTxp45nuKuB+fA4NPkoUMesp1gBg3xIaKgdAjsMfxsqHqT2XTKBHUrWiwwd5car/3PJ8W5Y7MZ7ZMxGFga0glBkpXHNbqraGFsQeRMx/mC4D+/YYQ6C6iRxDD3AZBmnV9fYDuH3ekf8IPxRhEbK9yWBT31XpVcMcaEhNqijZfSR2f+Expa3B89uBSx7v1vcEmwLSJgeqVrIhht6Nnlc=
  app: 'yes'
  on:
    repo: uva-cs3240-f19/project-101-loxodante
